### ISSUE TITLE
Suggestion: let OB C/C++(?), via ffi, parse the generated JSON and consume the model parameters for all the languages!

### ISSUE THREAD

**Issue by Buggaboo** [objectbox/objectbox-dart#121]
If there seems to be a [uniform JSON model](https://docs.objectbox.io/advanced/meta-model-ids-and-uids#json-for-consistent-ids), why not let the C just consume it to generate the proper models, then poop out the updates to the parameters again (in JSON)?

We can get [rid of model-related boilerplate in all languages](https://github.com/objectbox/objectbox-c/blob/master/include/objectbox.h#L279-L353).

I believe flatcc (dependency?) already has a JSON parser.

Even crazier idea: use flatbuffers, instead of JSON, so its (allegedly) backwards compatible, if that's an issue.

**Comment by vaind** [comment]
This has been discussed previously but isn't planned (for now) because any JSON loading would:
* mean you have to distribute the model.json with your app, be it as a file or part of the source code (as a string)
* be slower than a model constructed using classes - which the compiler can optimize/inline. Note: this isn't currently done in Dart either and we're still using some JSON parsing here but that should go away in the future
