### ISSUE TITLE
It is not possible to create nested ToMany relationship.

### ISSUE THREAD

**Issue by kamilklyta** [objectbox/objectbox-dart#203]
**Basic info (please complete the following information):**
 - ObjectBox Dart version: 0.12.1
 - Flutter/Dart SDK: 1.22.6
 - build_runner: 1.11.1
 - Reproducibility: always

**To Reproduce**
1. Run build_runner for the following code:
    ```dart
    @Entity()
    class TestA {
      int id;
    
      String text;
      final bs = ToMany<TestB>();
      TestA(this.text);
    }
    
    @Entity()
    class TestB {
      int id;
    
      String text;
      final cs = ToMany<TestC>();
      TestB(this.text);
    }
    
    @Entity()
    class TestC {
      int id;
    
      String text;
      TestC(this.text);
    }
    ```
2. Look at the console:
    ```
    [SEVERE] objectbox_generator:generator on lib/$lib$:
    
    Exception: lastRelationId 1:5306783115712194802 does not match relation 'bs' with id 1:3788192784102328492
    [INFO] Running build completed, took 10.0s
    
    [INFO] Caching finalized dependency graph...
    [INFO] Caching finalized dependency graph completed, took 78ms
    
    [SEVERE] Failed after 10.1s
    ```

**Expected behavior**
  
Nested `ToMany` relation should work 🤔

**Comment by vaind** [comment]
Thanks for reporting this, there was an issue with standalone relation ID generation. Fixed in `next` branch and will come out in a next 0.13 prerelease (maybe we'll also push a patch to 0.12 if we can't get a stable 0.13 out soon). I'll keep this open until the fix is released.

To get around the issue, you can manually edit the generated ID for now (in objectbox.g.dart and objectbox-model.json). If we took the message you've received as a source, I'd say replacing "1:5306783115712194802" with "2:5306783115712194802" should do the trick, but I would only suggest doing manual changes to the model.json and generated code as a last resort or in applications where you don't care about messing up your database (a.k.a when you're just trying stuff out).

**Comment by vaind** [comment]
The fix is out on all currently supported versions (0.11.2, 0.12.2, 0.13.0-nullsafety.1)
