### ISSUE TITLE
Failing to build a simple APK

### ISSUE THREAD

**Issue by Katekko** [objectbox/objectbox-dart#213]
I have an open project in my git that I upgrade the version to 2.0.3, now the project is unable to build an apk.
I don't know what to do, the error message is not clear to me...
The project works when you running, the error appear just when you try to build an APK
![image](https://user-images.githubusercontent.com/13632735/113038826-59dc3a80-916d-11eb-9dd7-aa511ec836cb.png)
Error with verbose: https://pastebin.ubuntu.com/p/Y9Q9gmJ8qd/

I discovered if you remove object box from project, the build works again, you will have to comment all the things (not so much) that use the object box.

I really don't know what to do, I'm only using object box now (before was hive), I really like the way the object box deals with things I hope you can help me to fix that.

```BASH
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

How can you reproduce the error:

1- Clone my repo: https://github.com/Katekko/ekko_app
2- Copy and paste the config.example.dart and change the name to config.dart
3- Try to build an apk: flutter build apk --release

I really don't know what to do, please help me :(

I've opened the same issue on flutter repo, but I found out the problem was object box:
The issue: https://github.com/flutter/flutter/issues/79093

**Comment by vaind** [comment]
Looks like this has something to do with inlining in Dart's AOT precompiler for ARM. At first, I thought it might be related to one of the `@pragma('vm:prefer-inline')` annotations (even though they're just hints and must not break the compiler) but that doesn't seem to be the case, because the compilation fails even if I remove all the annotations from objectbox-dart.

I'd say closing the issue in Flutter repo was a little premature - this looks like an issue in the compiler (I suspect some new optimizations for null-safe code being triggered) and even if we must do a change in objectbox-dart to circumvent the issue fo already released Flutter SDK versions, we'd first need to know what that is. Without the knowledge of the internals of Dart AOT compiler, this is pretty hard to figure out so I'd suggest you reopen the issue in Flutter's GitHub. Feel free to refer to this response.

**Comment by vaind** [comment]
I've been able to pinpoint an issue (https://github.com/flutter/flutter/issues/79441), but it doesn't seem to be the only one. Still looking for others.

**Comment by vaind** [comment]
Fixed by 0.13.1-dev.0 - should become 0.13.1 tomorrow but you can already try the pre-release version

**Comment by Katekko** [comment]
> Fixed by 0.13.1-dev.0 - should become 0.13.1 tomorrow but you can already try the pre-release version

You figure out how to fix it? Or was a workaround?

**Comment by vaind** [comment]
Flutter/Dart SDK devs must fix their compiler. I've just found the problematic code and changed it to an alternative that the compiler didn't have trouble with.

**Comment by vaind** [comment]
BTW 0.14.0 is out with the change
