### ISSUE TITLE
 Unhandled Exception: type 'MaquinaModel' is not a subtype of type 'EstanqueModel' of 'object'

### ISSUE THREAD

**Issue by hortigado** [objectbox/objectbox-dart#220]
Hi, Helpme I get it error to the add maquinas to EstanqueModel
```
@Entity(uid: 0)
class EstanqueModel {int? id;
  @Backlink()
  final maquinas = ToMany<MaquinaModel>();
}
@Entity(uid: 1)
class MaquinaModel {int? id;
  final estanqueMode = ToOne<EstanqueModel>();
}
 static Future<int?> addMaquina(MaquinaModel maquinaModel) async {
    /// Inserts the given [person] object into the box
    var store = await BoxStore.getStore();
    var box = store.box<EstanqueModel>();
    EstanqueModel estanqueModel = box.get(maquinaModel.estanqueId);
    estanqueModel.maquinas.add(maquinaModel);

    int customerId = box.put(maquinaModel);
    print(customerId);
    return customerId;
  }
```

**Comment by vaind** [comment]
What does the stack look like for the error? You're calling `box.put(maquinaModel)`, where `box` is of type `Box<EstanqueModel>` - you're putting to a wrong box. Using the right box will fix the issue.

Also, the whole code doesn't look right, you don't have to manually insert the ToMany side of the relation because it's just `Backlink` - there's actually no additional data in the database, it's managed automatically based on the other side, the `ToOne` in `MaquinaModel`. I'd propose a correct code but can't because the fields used in `addMaquina()` you've provided don't match entities declared above - there're no `estanqueId` or `.maquinas` fields.

BTW: why are you specifying `uid` explicitly? uid=0 is not a valid value and is actually replaced with an autogenerated one anyway (you can see for yourself in `objectbox-model.json`)

**Comment by vaind** [comment]
Actually, the code shouldn't even compile, because of that `box.put()`. If you could provide actual code that throws that exception, with the stack trace, I may be able to tell you what's wrong.

**Comment by hortigado** [comment]
Ohhh thanks i didn't realize i just changed
`    int customerId = box.put(maquinaModel);
`

> for

`    int customerId = box.put(estanqueModel);
`
