### ISSUE TITLE
What's causing the second else? (set target)

### ISSUE THREAD

**Issue by Katekko** [objectbox/objectbox-dart#285]
I'm doing this: 
![image](https://user-images.githubusercontent.com/13632735/125811552-7130c855-8101-4cee-8a34-0344e9440f21.png)

And every time is reaching the second else, doing my target getting null. That is something else that I need to do? 

![image](https://user-images.githubusercontent.com/13632735/125811114-4f1bb149-0d98-4837-b1fa-01eaa2219864.png)

**Comment by vaind** [comment]
Looks good to me. The third branch (`...unknown()`) says it is not known whether this is a new object (`id == 0`) or an existing one (`id != 0`), because it has no way to find out the ID yet, if the store hasn't been attached to this relation.
This is all just fine and the only limitation is you cannot access `toUserProfileEntity.user.targetId` yet, i.e. read the ID - same as above, it can't find out. 

When you call put on the base object, for example by `box.put(toUserProfileEntity)`, the model is made known to the `ToOne` relation and it finds out the ID is zero and puts the target as well, transparently. Afterwards `toUserProfileEntity.user.targetId` also starts working as expected, returning a non-zero ID of the just inserted `UserEntity`.

To help me understand your situation, could you maybe elaborate why reaching that third branch looks like an issue to you? Does it cause you any problems in your app?

BTW if you really wanted, you could call `toUserProfileEntity.user.attach(store)` manually before setting the target, though that's very rarely needed (as I've said above, only if you require `toUserProfileEntity.user.targetId` to work before you `put(toUserProfileEntity)`.

**Comment by Katekko** [comment]
Right, I will try to show step by step what's is going on to me:

First: I set the target
![image](https://user-images.githubusercontent.com/13632735/125818352-ac293373-ab6d-4496-b208-cef9e973bf1e.png)

In this step the strange to me is even the target was set the attribut is null;
![image](https://user-images.githubusercontent.com/13632735/125818520-69b5b809-9f21-4fb8-979b-ffb3646eec21.png)
![image](https://user-images.githubusercontent.com/13632735/125818560-91c7aa34-66b8-4819-a6bb-3bfe6cf86c1c.png)


Second: I save(put) the object (I guess with the target) and get the ID back
![image](https://user-images.githubusercontent.com/13632735/125818751-9f1bb4f3-2e4f-496f-bdee-a1862811620d.png)
![image](https://user-images.githubusercontent.com/13632735/125818796-1bebf7d1-6691-4410-8f6b-82dbadf24077.png)

Third: I'm trying to get again the object saved to see the relation, but without a success.
![image](https://user-images.githubusercontent.com/13632735/125819028-a919f1fd-605f-4910-9d2a-a79a00dde005.png)

I can uploud my code to you if you want to. Its a opensource project that I working on to create some clean architeture easy to understand.

**Comment by vaind** [comment]
> I can uploud my code for you if you want to. Its a opensource project that I working on to create some clean architeture easy to understand.

that would be the most efficient I guess - just let me know what to run

**Comment by Katekko** [comment]
> > I can uploud my code for you if you want to. Its a opensource project that I working on to create some clean architeture easy to understand.
> 
> that would be the most efficient I guess - just let me know what to run

https://github.com/Katekko/github-clean

You will need two things:

1. Copy and paste the config.example.dart and change the name to config.dart

2. Generate one access token to access the github API. That's no need any permission, the app is just to search and list the github users.

Tell me if you get any problem to run.

Now to reproduce the problem that is happening to me:

1. Go to user_profile.model.dart and break point the line 77
2. Open the app, will load some github users, click in anyone, will open the profile
3. Click in the heart to favorite an user, will trigger the save on file user_profile.model.dart.

**Comment by vaind** [comment]
damn that was so hard to debug.... you call this getter every time - and it creates a new object on every call, so the object you set .user.target on isn't the same one you save...

```dart
  UserProfileEntity get toUserProfileEntity {
    return UserProfileEntity(
      id: localProfileId,
      bio: bio,
      email: email,
      location: location,
      nickname: nickname,
    );
  }
  ```

**Comment by Katekko** [comment]
Thank you very much, awesome.

Idk how I missed this, thanks again

**Comment by vaind** [comment]
You're welcome
