### ISSUE TITLE
Improve developer experience - generated code

### ISSUE THREAD

**Issue by vaind** [objectbox/objectbox-dart#29]
Currently, binding code must be generated manually using `pub run build_runner build` before running/building an application

Is there a way this could be streamlined?

**Comment by GregorySech** [comment]
There is a nice Wiki entry about code generation in Flutter, it might be what you are looking for: https://github.com/flutter/flutter/wiki/Code-generation-in-Flutter
However I'm not sure if it does work in a generic Dart project.
Also there was a problem with this feature in the unstable channels and I'm not sure if has been fixed since 5 days ago https://github.com/flutter/flutter/issues/42003

**Comment by vaind** [comment]
`build_runner` seems to be the de-facto standard for code generation in Dart/Flutter these days. Even the linked page now says so:

> `flutter generate` is deprecated and slated to be removed in a future flutter release. `build runner` is now much easier to use directly, and can be used to generate code for flutter projects.

As there's no actionable item at the moment and the code generation doesn't seem to be a place of concern for the users, I'm closing this issue.
