### ISSUE TITLE
Type "var" or "dynamic" not supported in entity variable declaration

### ISSUE THREAD

**Issue by raphire08** [objectbox/objectbox-dart#293]
Create an Entity with `dynamic` or `var` as one of the fields. Run build runner. Build runner throws error. What could be the workaround to have a dynamic variable in entity class.

```
@Entity()
class Shape {
  Shape(this.var1, this.var2);

  int id = 0;

  var var1;

  dynamic var2;
}
```

Gettting this warning
[WARNING] objectbox_generator:resolver on lib/entity/shape_temp.dart:
  skipping property 'var1' in entity 'Shape', as it has an unsupported type: 'dynamic'
[WARNING] objectbox_generator:resolver on lib/entity/shape_temp.dart:
  skipping property 'var2' in entity 'Shape', as it has an unsupported type: 'dynamic'

**Comment by vaind** [comment]
To be able to store the data in binary format (as used by the database), it has to be typed statically, otherwise, the generator doesn't know how to create the right code to serialize the variable.

On the other hand, you **can** write about anything, just convert it to one of the known formats (e.g. serialize yourself using JSON to a string/blob). You can read up on how to do so in the docs: https://docs.objectbox.io/advanced/custom-types

**Comment by vaind** [comment]
Supporting dynamic types isn't in scope, at least not at the moment. As said above, converters are an alternative. If there are more questions, feel free to reopen.
