### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol (undefined symbol: obx_version_is_at_least )

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#346]
After updating to latest version I am getting the above error.

**Comment by greenrobot-team** [comment]
Can you please share more about your setup? Filling out the issue template would help.

If this is for a Dart CLI app, this may be caused by an outdated objectbox-c library.

If this is a Flutter app, check if your project overrides any Android or iOS dependencies and update them to the latest versions.

**Comment by vaind** [comment]
Duplicate of #252
