### ISSUE TITLE
Need a way to read / write from iOS native code

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [objectbox/objectbox-dart#383]
I need to save & read data from iOS native code and from the iOS service extension.
Is it possible now..?

**Comment by greenrobot-team** [comment]
Thanks for your inquiry. My first question is, why do you need this? Why does the Flutter/Dart API not work for you?

If you still want to do this, you might try the new Store attach API that is part of the latest ObjectBox for Swift release 1.7.0 (also depended on by the latest ObjectBox for Dart 1.4.0 release). Use it instead of the usual way to create a Store in Swift. Use it after opening a Store in Dart/Flutter to attach to that same store instance.

However, this requires to maintain a Swift copy of your Dart model classes so the same database model is generated. You can verify it's the same by checking if the `objectbox-model.json` files are the same.

Let me know if you have questions.
