### ISSUE TITLE
@Unique annotation ignored 

### ISSUE THREAD

**Issue by FDuhen** [objectbox/objectbox-dart#449]
```@Unique``` annotation not working as expected since I can add multiple objects with the same ```@Unique``` value .  

### Basic info 

- ObjectBox version: 1.6.0
- Flutter/Dart SDK: 3.0.1
- Null-safety enabled: yes
- Reproducibility: always
- OS: macOs Monterey 
- Device/Emulator: Emulator

### Steps to reproduce

1. Create a basic entity to store in a Box with a Unique field 

```dart
@Entity()
class MainEntity {
  int id = 0;

  @Unique(onConflict: ConflictStrategy.replace)
  String? name;
}
```

2. Create a box following the official documentation  

```dart
  late final Box<MainEntity> mainEntityBox;

  ObjectBox._create(this.store) {
    mainEntityBox = Box<MainEntity>(store);
  }
```

3. Add multiple times an object with the same ```@Unique``` ID  
```dart
class ObjectBoxPageState extends State<ObjectBoxPage> {

  List<MainEntity>? datasInStore;

  @override
  Widget build(BuildContext context) {
    datasInStore = objectbox.mainEntityBox.getAll();

    return Scaffold(
      body: InkWell(
        onTap: () {
          final item = MainEntity()..name = 'Toto';
          objectbox.mainEntityBox.put(item);

          setState((){});
        },
        child: Center(
          child: Text("${datasInStore?.length} datas saved"),
        ),
      ),
    );
  }
}
```

### Expected behavior

I'd expect the box to always retrieve 1 item since my ```@Unique``` key is always 'Toto', but it keeps adding new items every-time I call the ```.put``` method.

**Comment by greenrobot-team** [comment]
Appears you have already figured it out, but your code sets `@Unique(onConflict: ConflictStrategy.replace)`. This means instead of an exception on conflict, an existing object is deleted, then the new one inserted.

**Comment by AdelKanso** [comment]
@greenrobot-team is there an option to update instead of deleting and inserting a new one, cause if there's other data who has relation to this specific object, they gonna lose the relation.
ex:
note : uuid is unique with replace conflict strategy
RelatedObject test has ToOne relation ship to Test class

Test{ id:1, uuid: "asdsa_asd_Asd"}
RelatedObject{id:1, test: (relation to test object with id 1)}
if a confilt happen while inserting a new "Test" object (an existed uuid exist), the old "Test" will be deleted, a new one inserted with a different primary key id which is in this case 2,
Test{ id:2, uuid: "new_uuid"}
so RelatedObject gonna lose the relation to the Test object

**Comment by AdelKanso** [comment]
similar to this https://github.com/objectbox/objectbox-java/issues/509#issue-344473626

**Comment by AdelKanso** [comment]
@greenrobot-team

**Comment by greenrobot-team** [comment]
@AdelKanso There is no `update` strategy. However, you can write code that gets an object by id (or multiple), changes its properties and puts it again.
