### ISSUE TITLE
Unhandled Exception: Bad state: object put failed: 10001 Can not modify object of sync-enabled type "User" because sync has not been activated for this store.

### ISSUE THREAD

**Issue by Aaron009** [objectbox/objectbox-dart#458]
run error message:
```shell
Unhandled Exception: Bad state: object put failed: 10001 Can not modify object of sync-enabled type "User" because sync has not been activated for this store.
```

### Steps to reproduce
1: Open the example project folder and run it normally.
2: Delete the `objectbox.g.dart` and `objectbox-model.json` files.
3: Execute `flutter pub run build_runner build`, after generating the file, run it again and run the error message as shown above.

**Comment by greenrobot-team** [comment]
I assume your project is using ObjectBox with [Sync](https://sync.objectbox.io/)? Make sure that you have added `objectbox_sync_flutter_libs` instead of `objectbox_flutter_libs` to your dependencies as [noted in the README](https://pub.dev/packages/objectbox#flutter).

If your project is not using Sync, remove [the `@Sync` annotation](https://sync.objectbox.io/sync-client#enable-your-objects-for-objectbox-sync) from the `User` object.

**Comment by Aaron009** [comment]
After I delete the @Sync annotation, re-execute `flutter pub run build_runner build` to solve this problem
