### ISSUE TITLE
Dsym files not present in Release mode of ObjectBox Dart

### ISSUE THREAD

**Issue by ankitagarwal007** [objectbox/objectbox-dart#597]
### Build info

- objectbox version: 2.2.0
- Flutter/Dart version: [e.g. 3.1.0, see `flutter --version` or `dart --version`]
- Build OS: [e.g. Ubuntu 22.04 | Windows 11 | macOS 10.16 ]
- Deployment OS or device: iOS

### Steps to reproduce

1. Compile ObjectBox.xcframework for Release
2. There is a empty dSyms folder but no dsym file is present
3. This is causing issues as empty directories are not tracked in git. So empty Dsyms folder is getting ignored. 
4. Build is failing because as per Info.plist file there is a dsym path which is not availabel

**Comment by ankitagarwal007** [comment]
Hi 

We are using the below.

flutter build ios-framework --xcframework --no-debug --no-profile --output=../Js/Flutter

**Comment by greenrobot-team** [comment]
Thanks! I verified that e.g. `ObjectBox.xcframework\ios-arm64\dSYMs\` folders are empty and they are included in `ObjectBox.xcframework\Info.plist`.

If it makes a difference, based on the build command it looks like [Flutter is integrated into an existing iOS app](https://docs.flutter.dev/add-to-app/ios/project-setup).

For us to check:
- should our build actually include debug symbols (e.g. due to a misconfiguration the debug symbols are not copied when publishing to CocoaPods)
- if not, can it be configured that these directories are not configured in `ObjectBox.xcframework\Info.plist`
- or at last if this is a Flutter tooling issue.

**Comment by greenrobot-team** [comment]
@ankitagarwal007 So I tried running building our [relations example app](https://github.com/objectbox/objectbox-dart/tree/main/objectbox/example/flutter/objectbox_demo_relations) with this command:

```
flutter build ios-framework --no-debug --no-profile --output=test-ios-framework
```

And besides a warning to turn off "Enable Bitcode" there are no other warnings or errors. This is using Xcode 15.0.1 on macOS 13.6.

Again, could you please share the error output of the build command?

**Comment by ankitagarwal007** [comment]
The output command doesn’t give any error but when we commit our main app, and take a fresh checkout it doesn’t compile because empty folders of dSym doesn’t get committed.

**Comment by greenrobot-team** [comment]
@ankitagarwal007 Thanks for clarifying!

You are probably aware, but a workaround would be to add a `.gitkeep` file to those directories (or not check in the `Pods` directory at all).

**Comment by ankitagarwal007** [comment]
Hi Team,

We currently do this only, but we must do it whenever we compile it. So it would be better if the object box framework either includes Dsym files or removes the path from Info.plist file

**Comment by greenrobot-team** [comment]
[The latest release](https://github.com/objectbox/objectbox-dart/releases/tag/v2.5.0) depends on a new ObjectBox Pod that includes debug symbol files.

Let us know if this resolves your issue!
