### ISSUE TITLE
Async property query returns result too early

### ISSUE THREAD

**Issue by Buggaboo** [objectbox/objectbox-dart#70]
If you run the branch #51 and #58, and compare the `count` and `find` result on the `PropertyQuery`, you'll find that the `find` function sometimes returns a partially correct result set, with certain random bytes (every time you run it), that are the same as the random bytes as `count` consistently returns.

This leads me to think that these obx functions return via ffi before the actual correct values are populated on the array alloc. This reminds me of the async `await` the `Future` discussion #49 .

**Comment by Buggaboo** [comment]
In the meantime, the users should `sum`, `avg`, etc. on Entity attributes, using, higher-order dart functions on collections, e.g.:

```dart
// sum
final sum = box.getAll().map((s) => s.someIntegerAttribute ?? 0).toList().reduce((a,b) => a + b);
final avg  = sum / box.count();
```

**Comment by vaind** [comment]
There is no async property query. The native call is synchronous, it cannot return before the data is ready. 

I've found the issue causing wrong results of `find()` - it's a regression in `OBX_id_array::items()` introduced during the conversion to dart2.6. It stopped returning a copy of the list, as the comment said and returned a reference to the original list. You've used this method as a template when implementing the other obx_*_array structs, thus replicating this problem.
See 7641c8550c4f72be5badc93179d169c7be00346d for a fix.

Closing this issue, let's address the rest (if there are any more problems) in a property-query PR. 

BTW regarding all the OBX_*_array structs - could a generic be used instead of having a copy of each? That should also reduce the amount of duplication in the caller code
